project:
  type: website

website:
  title: "MSNI Stats Tips"
  navbar:
    right:
      - text: All Posts
        href: index.qmd
  google-analytics: "G-RQ4NY7VSS4"

format:
  html:
    page-layout: article
    code-fold: true
    code-tools: true
    code-block-bg: "white"
    code-block-border-left: "#31BAE9"
    code-line-numbers: true
    code-copy: true
    toc: true
    toc-depth: 3
    number-sections: true
    df-print: kable
    fontsize: 1.1em
    fig-height: 9
    fig-width: 12
    theme:
      light: united
      dark: darkly
    highlight-style: kate
    css: styles.css

editor: visual

