project:
  type: website

website:
  title: "MSNI Weekly Stats Tips"
  navbar:
    right:
      - text: All Posts
        href: index.qmd
      - icon: github
        href: https://github.com/
format:
  html:
    theme:
      light: united
      dark: darkly
    highlight-style: dracula
    css: styles.css

editor: visual

